apiVersion: 1

datasources:
  - name: Greecon TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: greecon
    user: greecon_local
    secureJsonData:
      password: greecon_local_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
